# Generated by Django 3.2.6 on 2022-06-30 21:36

import apps.profiles.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='profile_pic/default.png', upload_to='profile_pic')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('tel', models.CharField(max_length=13, null=True, validators=[apps.profiles.validators.validate_only_number_field])),
                ('address', models.CharField(max_length=150, null=True)),
                ('scholarship', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('T', 'Tecnólogo'), ('S', 'Ensino Superior'), ('M', 'Mestrado'), ('D', 'Doutorado')], max_length=1, null=True)),
                ('role', models.CharField(choices=[('F', 'FrontEnd'), ('B', 'BackEnd'), ('DB', 'Banco de Dados'), ('T', 'Tester'), ('DO', 'DevOps')], max_length=2, null=True)),
                ('about_me', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('cep', models.CharField(max_length=8, null=True, validators=[apps.profiles.validators.validate_only_number_field])),
                ('description', models.TextField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
