# Generated by Django 3.2.6 on 2022-07-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_job_closed'),
        ('profiles', '0002_auto_20220701_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(choices=[('a1', 'Até R$1.000,00'), ('1a2', 'De R$1.000,00 a R$2.000,00'), ('2a3', 'De R$2.000,00 a R$3.000,00'), ('3+', 'Acima de R$3.000,00')], max_length=3)),
                ('experience', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'Apply',
                'unique_together': {('job', 'employee')},
            },
        ),
    ]
