# Generated by Django 3.2.6 on 2022-07-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20220701_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('salary', models.CharField(choices=[('a1', 'Até R$1.000,00'), ('1a2', 'De R$1.000,00 a R$2.000,00'), ('2a3', 'De R$2.000,00 a R$3.000,00'), ('3+', 'Acima de R$3.000,00')], max_length=3)),
                ('description', models.TextField()),
                ('scholarship', models.CharField(choices=[('F', 'Ensino Fundamental'), ('M', 'Ensino Médio'), ('T', 'Tecnólogo'), ('S', 'Ensino Superior'), ('M', 'Mestrado'), ('D', 'Doutorado')], max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.company')),
            ],
        ),
    ]
